# Generated by Django 4.2.4 on 2023-08-19 21:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolar', '0002_remove_binance_coin_remove_binance_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(default=datetime.datetime(2023, 8, 19, 18, 57, 38, 236525))),
            ],
        ),
    ]
