# Generated by Django 4.2.4 on 2023-08-27 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolar', '0007_alter_update_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 17, 36, 8, 629831)),
        ),
    ]
