# Generated by Django 4.2.4 on 2023-08-29 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolar', '0009_alter_update_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 23, 26, 18, 345467)),
        ),
    ]
