# Generated by Django 4.2.4 on 2023-09-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolar', '0012_alter_update_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiat',
            name='data_last',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
