# Generated by Django 4.2.2 on 2023-08-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
