# Generated by Django 4.2.4 on 2023-08-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, default='https://imgur.com/a/IcFqDOI', max_length=200, null=True),
        ),
    ]
