# Generated by Django 4.2.4 on 2023-08-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_userprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.CharField(blank=True, default='https://i.imgur.com/nkeHzfl.png', max_length=200, null=True),
        ),
    ]
