# Generated by Django 4.2.4 on 2023-09-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_alter_userprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
