# Generated by Django 4.2.2 on 2023-07-01 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrumento', '0010_alter_especie_especie_delete_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotiz_mep', models.FloatField()),
                ('operacion', models.CharField(choices=[('Venta', 'Venta'), ('Compra', 'Compra'), ('Dividendo', 'Dividendo'), ('Renta', 'Renta'), ('Amortización', 'Amortización')], default='Compra', max_length=12)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='ARS', max_length=3)),
                ('cantidad', models.IntegerField()),
                ('precio_ars', models.FloatField()),
                ('precio_usd', models.FloatField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones', to='instrumento.especie')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones', to='instrumento.tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Operaciones',
            },
        ),
    ]
