# Generated by Django 4.2.2 on 2023-07-03 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 20, 37, 14, 217926)),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='operacion',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta'), ('Dividendo', 'Dividendo'), ('Renta', 'Renta'), ('Amortización', 'Amortización')], default='Compra', max_length=12),
        ),
    ]
