# Generated by Django 4.2.2 on 2023-07-04 02:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0012_alter_activo_options_alter_especie_options_and_more'),
        ('cartera', '0002_alter_operacion_fecha_alter_operacion_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='moneda',
        ),
        migrations.AddField(
            model_name='operacion',
            name='activo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones', to='instrumento.activo'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 23, 4, 7, 378877)),
        ),
    ]
