# Generated by Django 4.2.2 on 2023-07-15 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_operacion_plazo_alter_operacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
