# Generated by Django 4.2.2 on 2023-08-01 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_operacion_total_ars_operacion_total_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
