# Generated by Django 4.2.2 on 2023-06-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('tipo', models.CharField(max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('plazo', models.CharField(max_length=4)),
                ('moneda', models.CharField(max_length=3)),
                ('apertura', models.FloatField()),
                ('ultimo', models.FloatField()),
                ('cierre_ant', models.FloatField()),
                ('cierre', models.FloatField()),
                ('var', models.FloatField()),
                ('hora', models.DateTimeField()),
            ],
        ),
    ]
