# Generated by Django 4.2.2 on 2023-06-20 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrumento', '0002_remove_especie_cierre_remove_especie_moneda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotiz_mep', models.FloatField()),
                ('operacion', models.CharField(choices=[('V', 'Venta'), ('C', 'Compra'), ('D', 'Dividendo'), ('R', 'Renta'), ('A', 'Amortizacion')], default='C', max_length=12)),
                ('cantidad', models.IntegerField()),
                ('precio_ars', models.FloatField()),
                ('precio_usd', models.FloatField()),
                ('total_ars', models.FloatField()),
                ('total_usd', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones_ticker', to='instrumento.especie')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones_tipo', to='instrumento.especie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
