# Generated by Django 4.2.2 on 2023-06-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0003_operacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ('tipo', 'ticker')},
        ),
        migrations.AlterModelOptions(
            name='operacion',
            options={'verbose_name_plural': 'Operaciones'},
        ),
        migrations.AlterField(
            model_name='especie',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumento.tipo'),
        ),
    ]
