# Generated by Django 4.2.2 on 2023-06-20 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0004_tipo_alter_especie_options_alter_operacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones_tipo', to='instrumento.tipo'),
        ),
    ]
