# Generated by Django 4.2.2 on 2023-06-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0005_alter_operacion_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ('tipo', 'especie')},
        ),
        migrations.RenameField(
            model_name='especie',
            old_name='ticker',
            new_name='especie',
        ),
        migrations.AlterField(
            model_name='operacion',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones_especie', to='instrumento.especie'),
        ),
    ]
