# Generated by Django 4.2.2 on 2023-06-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0006_alter_especie_options_rename_ticker_especie_especie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='ticker',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.DeleteModel(
            name='Operacion',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
