# Generated by Django 4.2.2 on 2023-06-24 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrumento', '0007_remove_operacion_ticker_remove_operacion_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=5)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('plazo', models.CharField(max_length=4)),
                ('apertura', models.FloatField()),
                ('ultimo', models.FloatField()),
                ('cierre_ant', models.FloatField()),
                ('var', models.FloatField()),
                ('hora', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ('tipo', 'especie'),
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotiz_mep', models.FloatField()),
                ('operacion', models.CharField(choices=[('V', 'Venta'), ('C', 'Compra'), ('D', 'Dividendo'), ('R', 'Renta'), ('A', 'Amortizacion')], default='C', max_length=12)),
                ('cantidad', models.IntegerField()),
                ('precio_ars', models.FloatField()),
                ('precio_usd', models.FloatField()),
                ('total_ars', models.FloatField()),
                ('total_usd', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones_especie', to='instrumento.especie')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operaciones_tipo', to='instrumento.tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Operaciones',
            },
        ),
        migrations.AddField(
            model_name='especie',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumento.tipo'),
        ),
    ]
