# Generated by Django 4.2.2 on 2023-06-25 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='instrumento.tipo'),
        ),
    ]
