# Generated by Django 4.2.2 on 2023-06-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0009_alter_especie_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='especie',
            field=models.CharField(help_text='5 caracteres máx.', max_length=5),
        ),
        migrations.DeleteModel(
            name='Operacion',
        ),
    ]
