# Generated by Django 4.2.2 on 2023-07-03 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0010_alter_especie_especie_delete_operacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='nombre',
        ),
        migrations.AddField(
            model_name='especie',
            name='moneda',
            field=models.CharField(default='ARS', help_text='3 caracteres máx.', max_length=3),
        ),
        migrations.AlterField(
            model_name='especie',
            name='plazo',
            field=models.CharField(default='48hs', max_length=4),
        ),
        migrations.AlterField(
            model_name='especie',
            name='ultimo',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_ars', models.CharField(help_text='5 caracteres máx.', max_length=5)),
                ('ticker_mep', models.CharField(help_text='5 caracteres máx.', max_length=5)),
                ('ticker_ccl', models.CharField(help_text='5 caracteres máx.', max_length=5)),
                ('nombre', models.CharField(max_length=120)),
                ('mercado', models.CharField(max_length=20)),
                ('ratio', models.FloatField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='instrumento.tipo')),
            ],
        ),
    ]
