# Generated by Django 4.2.2 on 2023-07-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0012_alter_activo_options_alter_especie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='maximo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='especie',
            name='minimo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='especie',
            name='monto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='especie',
            name='punta_compra',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='especie',
            name='punta_venta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='especie',
            name='volumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='especie',
            name='apertura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='especie',
            name='cierre_ant',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='especie',
            name='var',
            field=models.FloatField(default=0.0),
        ),
    ]
