# Generated by Django 4.2.2 on 2023-07-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0013_especie_maximo_especie_minimo_especie_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='ticker_usa',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ticker_ccl',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ticker_mep',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5),
        ),
    ]
