# Generated by Django 4.2.2 on 2023-07-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0014_activo_ticker_usa_alter_activo_ticker_ccl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie_USA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(help_text='5 caracteres máx.', max_length=5)),
                ('nombre', models.CharField(max_length=40)),
                ('ultimo', models.FloatField(default=0.0)),
                ('var', models.FloatField(default=0.0)),
                ('hora', models.CharField(max_length=23)),
            ],
            options={
                'verbose_name_plural': 'Especies_USA',
                'ordering': ('especie',),
            },
        ),
    ]
