# Generated by Django 4.2.2 on 2023-08-01 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0015_especie_usa'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='especie_usa',
            name='actualizado',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
