# Generated by Django 4.2.2 on 2023-08-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0016_especie_actualizado_especie_usa_actualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='ticker_ars',
            field=models.CharField(help_text='5 caracteres máx.', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ticker_ccl',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ticker_mep',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ticker_usa',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='especie_usa',
            name='especie',
            field=models.CharField(help_text='5 caracteres máx.', max_length=5, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='especie',
            unique_together={('especie', 'plazo')},
        ),
    ]
