# Generated by Django 4.2.2 on 2023-08-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0017_alter_activo_ticker_ars_alter_activo_ticker_ccl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='ticker_ccl',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ticker_mep',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ticker_usa',
            field=models.CharField(blank=True, help_text='5 caracteres máx.', max_length=5, null=True, unique=True),
        ),
    ]
