# Generated by Django 4.2.4 on 2023-08-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0019_alter_activo_ticker_ccl_alter_activo_ticker_mep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
    ]
