# Generated by Django 4.2.4 on 2023-08-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0020_activo_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie_usa',
            name='activo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='instrumento.activo'),
        ),
    ]
