# Generated by Django 4.2.4 on 2023-08-29 02:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0022_remove_especie_usa_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='especie',
            name='volumen',
            field=models.BigIntegerField(default=0),
        ),
    ]
