# Generated by Django 4.2.4 on 2023-09-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumento', '0025_alter_especie_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nasdaq_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
            ],
        ),
    ]
